# permissions for end users to view ovms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovms-viewer-role
rules:
- apiGroups:
  - intel.com
  resources:
  - modelserver
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - intel.com
  resources:
  - modelserver/status
  verbs:
  - get
