apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ovms-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Operator for OpenVINO Model Server
  displayName: OVMS
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - AI Inference OpenVINO
  links:
  - name: Ovms Operator
    url: https://ovms-operator.domain
  maturity: alpha
  provider:
    name: Intel
    url: https://github.com/openvinotoolkit/model_server
  version: 0.0.0
